### ISSUE TITLE
you are refreshing the canvas every screen change

### ISSUE THREAD

**Issue by alffanclub** [AlexanderOcias/UnityPixelArtCamera#1]
Nice approach to this problem.  I like the way you solved it, but I did notice one minor issue.  Currently in  `SetupRenderTexture` in "UnityPixelArtCamera/Assets/Ocias/PixelArtCamera/PixelArtCamera.cs", instead of setting the camera if it _is_ null, you overwrite the camera only if it is _not_ null. I'm mostly sure you want the opposite.  `if (mainCanvas != null)` to actually be `if (mainCanvas == null)`

**Comment by AlexanderOcias** [comment]
Whoops! Fixed, thank you!
