### ISSUE TITLE
Parts of the game shakes screen

### ISSUE THREAD

**Issue by Saishy** [AlexanderOcias/UnityPixelArtCamera#4]
In this first image you can see that only on that X area of a few pixels, moving inside it will make the character start shaking:
![2018-04-25_23-01-37](https://user-images.githubusercontent.com/2012108/39282300-2b2dc214-48df-11e8-86df-7bf857d22868.gif)

In this second image you can see that some specific objects will always be distorted, this one is the letter O on the text:
![2018-04-25_22-53-35](https://user-images.githubusercontent.com/2012108/39282325-4d6c4ddc-48df-11e8-9992-826f0d22c155.gif)

I can't see any reason for them to be like that.

**Comment by AlexanderOcias** [comment]
I'm not sure why your character is shaking there, it is usually an issue related to the camera set-up (you can even see a lot of jitter in Super Mario World), but your camera looks locked, so it shouldn't be happening... If you've already got your camera code in LateUpdate, please send me a repro project.

As for the the text distortion, I have some ideas why that may be happening. Try using this shader for that text: [PixelArtFontWorldSpace.shader.zip](https://github.com/AlexanderOcias/UnityPixelArtCamera/files/1949552/PixelArtFontWorldSpace.shader.zip) if it doesn't fix the issue, include this problem in the repro project too.

**Comment by Saishy** [comment]
Can you send me a way to contact you privately to send the repository? I
will send my game repo.

**Comment by AlexanderOcias** [comment]
Sure, you can reach me at aocias at gmail dot com

**Comment by AlexanderOcias** [comment]
I've managed to track down the reason behind the character shaking - it's affected by snapping in view-space instead of world-space. Looking into a solution...

**Comment by Saishy** [comment]
It's working perfectly now!

![Gif of game working without jitter](https://i.imgur.com/xAQ92HK.gifv)

Thank you very much! Is there anything I could do to help?

**Comment by AlexanderOcias** [comment]
Great! Nah I think it's all good at the moment, thanks for offering though!

As for the text issue, I'm fairly confident it is an issue with that specific font that I'm not able to detect or completely compensate for on my end. The character rects of that font aren't pixel-aligned to the texture, and are inconsistent between letters. Some of the cases of that can be fixed by a shader, but the cleanest solution might be to regenerate the font asset, or use a different font unfortunately.

**Comment by Saishy** [comment]
Ah I forgot to say, I made a ttf out of the font (since it was a bitmap I bought) and reimported into unity and that fixed it!
